# Generated by Django 5.1.4 on 2025-01-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_movement',
            name='movement_type',
            field=models.CharField(choices=[('In', 'In'), ('Out', 'Out')], max_length=50),
        ),
    ]
