# Generated by Django 5.1.4 on 2025-01-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0003_alter_stock_movement_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=50, null=True),
        ),
    ]
