# Generated by Django 5.1.4 on 2025-01-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0004_alter_sales_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
